name: Display jgitver version

on: [workflow_dispatch]


jobs:
  
  display_version:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # include all history and tags
          
      - name: checkout does not include tag annotation
        run: git fetch --force --tags
        
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: display git log
        run: git log

      - name: display version
        run: gradle version
        
      - name: job output
        run: |
          echo "## JGitVer project version:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          gradle version >> $GITHUB_STEP_SUMMARY

    
    
  
